# Generated by Django 3.2.12 on 2022-02-22 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import endearapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=60, primary_key=True, serialize=False, unique=True, verbose_name='email')),
                ('profile_image', models.TextField(default='/static/img/avatar.jpg', max_length=250)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', endearapp.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CrushModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.TextField(max_length=120)),
                ('crush_name', models.TextField(max_length=120)),
                ('crush_email', models.TextField(max_length=120)),
                ('record_date', models.DateField()),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crushes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'crush',
                'verbose_name_plural': 'crushes',
                'db_table': 'crush',
                'ordering': ('original_user', 'crush_name', 'crush_email', 'record_date'),
            },
        ),
    ]
