# Generated by Django 3.2.12 on 2022-02-20 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endearapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrushModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crush_name', models.TextField(max_length=120, unique=True)),
                ('crush_email', models.TextField(max_length=120, unique=True)),
                ('record_date', models.DateField()),
                ('original_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crushes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'crush',
                'verbose_name_plural': 'crushes',
                'db_table': 'crush',
                'ordering': ('original_user', 'crush_name', 'crush_email', 'record_date'),
            },
        ),
    ]
